### ISSUE TITLE
Sample code for home assistant automations?

### ISSUE THREAD

**Issue by repiuk** [elad-bar/ha-shinobi#32]
I have no idea how to use the select entity in home assistant automations. Some samples in the readme / documentation would be great.

```
Select
Allow to control the monitor mode:
    stop (Disabled)
    start (Watch-Only)
    record (Record)
```
PS Shinobi is amazing. I'm recording 1080P streams on the smallest NUC (Celeron, 4Gb) without any problems!

**Comment by elad-bar** [comment]
@repiuk examples for automation using SELECT component available in HA website and forum,
Same for all out-of-the-box component,
Using that component you get new integrations that uses the basic components by HA

**Comment by repiuk** [comment]
Ok found it with the help of the services tab in developer tools. If you know what to search for it's easy. I was unaware of the select.select_option service
  
 ```
 - service: select.select_option
      data:
        option: record
      target:
        entity_id: select.shinobi_video_mydevice_mode
```
