### ISSUE TITLE
2.0.24: broken feeds

### ISSUE THREAD

**Issue by robertklep** [elad-bar/ha-shinobi#39]
After the 2.0.24 update my browser console is showing 404 responses for both my monitor feeds.

YAML:
```
type: picture-elements
elements:
  - type: image
    entity: camera.shinobi_video_oprit
    camera_image: camera.shinobi_video_oprit
    camera_view: live
```

Reverting to 2.0.23 made them re-appear again.

Let me know if you want me to post more debugging info.
