### ISSUE TITLE
Invalid Server Details (debug enabled)

### ISSUE THREAD

**Issue by bullmoose20** [elad-bar/ha-shinobi#42]
2022-12-28 18:41:24.199 DEBUG (MainThread) [custom_components.shinobi.config_flow] Starting async_step_user of Shinobi Video
2022-12-28 18:41:24.204 DEBUG (MainThread) [custom_components.shinobi.configuration.managers.configuration_manager] Validate login
2022-12-28 18:41:24.204 INFO (MainThread) [custom_components.shinobi.component.api.api] Initializing Shinobi Video
2022-12-28 18:41:24.205 INFO (MainThread) [custom_components.shinobi.core.api.base_api] Performing login
2022-12-28 18:41:24.205 DEBUG (MainThread) [custom_components.shinobi.component.api.api] POST http://192.168.2.242:8383/?json=true, Url Encoded: False
2022-12-28 18:41:24.227 DEBUG (MainThread) [custom_components.shinobi.component.api.api] Status of http://192.168.2.242:8383/?json=true: 200
2022-12-28 18:41:24.235 DEBUG (MainThread) [custom_components.shinobi.component.api.api] GET http://192.168.2.242:8383/6b7e8c15b2f81bea496505cffc11bdb3/api/ucH7i6yZnt/list
2022-12-28 18:41:24.244 DEBUG (MainThread) [custom_components.shinobi.component.api.api] Status of http://192.168.2.242:8383/6b7e8c15b2f81bea496505cffc11bdb3/api/ucH7i6yZnt/list: 200
2022-12-28 18:41:24.245 ERROR (MainThread) [custom_components.shinobi.component.api.api] Login attempt failed, Error: 'str' object has no attribute 'get', Line: 293
2022-12-28 18:41:24.253 WARNING (MainThread) [custom_components.shinobi.config_flow] Failed to create integration, Error: invalid_server_details
2022-12-28 18:41:25.510 DEBUG (MainThread) [custom_components.shinobi.config_flow] Starting async_step_user of Shinobi Video
2022-12-28 18:41:25.530 DEBUG (MainThread) [custom_components.shinobi.configuration.managers.configuration_manager] Validate login
2022-12-28 18:41:25.530 INFO (MainThread) [custom_components.shinobi.component.api.api] Initializing Shinobi Video
2022-12-28 18:41:25.530 INFO (MainThread) [custom_components.shinobi.core.api.base_api] Performing login
2022-12-28 18:41:25.531 DEBUG (MainThread) [custom_components.shinobi.component.api.api] POST http://192.168.2.242:8383/?json=true, Url Encoded: False
2022-12-28 18:41:25.549 DEBUG (MainThread) [custom_components.shinobi.component.api.api] Status of http://192.168.2.242:8383/?json=true: 200
2022-12-28 18:41:25.557 DEBUG (MainThread) [custom_components.shinobi.component.api.api] GET http://192.168.2.242:8383/eef5be77b9eb65a38a33b84b7c0ca80a/api/ucH7i6yZnt/list
2022-12-28 18:41:25.563 DEBUG (MainThread) [custom_components.shinobi.component.api.api] Status of http://192.168.2.242:8383/eef5be77b9eb65a38a33b84b7c0ca80a/api/ucH7i6yZnt/list: 200
2022-12-28 18:41:25.565 ERROR (MainThread) [custom_components.shinobi.component.api.api] Login attempt failed, Error: 'str' object has no attribute 'get', Line: 293
![image](https://user-images.githubusercontent.com/12549033/209885535-007d9454-8021-4e9c-bbf5-5f63346dc6d6.png)

**Comment by elad-bar** [comment]
What version of Shinobi are you using (docker / standalone)? From which branch? 

Thanks

**Comment by bullmoose20** [comment]
Docker on Unraid.
________________________________

**Comment by bullmoose20** [comment]
Latest
________________________________

**Comment by elad-bar** [comment]
Can you provide the full docker image name?

Thanks

**Comment by bullmoose20** [comment]
This is what I have in Unraid settings: spaceinvaderone/shinobi_pro_unraid:latest
________________________________

**Comment by elad-bar** [comment]
As suspected, this is not official release of Shinobi Video which makes it impossible for me to support it,
I can suggest a workaround that might work, set the number of days to keep videos in case it is on default value

**Comment by bullmoose20** [comment]
I set it from 28 up to 30. Let’s see what happens


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by elad-bar** [comment]
if it was on default and you have changed it, just restart HA and it might work,
if it is not working I think it's best to switch to the official image,
just let me know if you would like assistant on the transition to the official image.

**Comment by bullmoose20** [comment]
When you say official image, can you please elaborate? I am not sure what you mean exactly…

My setup is that I have HA running on Unraid and I have Shinobi running on Unraid. My HA talks to everything pretty much on my Unraid server… I am a little confused.

Thanks,
Nick

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by elad-bar** [comment]
ok, sorry for not being clear about what is official,
the Shinobi Video is being maintained in GitLab, when code is being released the CICD pipeline in GitLab is building docker images from it and publish them.

the docker image you are using is outdated, from a year ago
![image](https://user-images.githubusercontent.com/3207137/209993589-19d2faf6-a347-4993-8a93-e403af382d97.png)

GitHub being that docker image was removed:
https://github.com/SpaceinvaderOne/shinobi_pro
![image](https://user-images.githubusercontent.com/3207137/209993686-070bb77a-203a-49dd-b41e-be9aafec89e1.png)

the GitLab official repository is [here](https://gitlab.com/Shinobi-Systems/Shinobi),
more details on how to install using docker available [here](https://gitlab.com/Shinobi-Systems/Shinobi/-/tree/dev/Docker),
below is an example docker-compose to run it:
```yaml
version: "3.9"

services:
  shinobi:
    image: registry.gitlab.com/shinobi-systems/shinobi:nvidia-dev #registry.gitlab.com/shinobi-systems/shinobi:dev
    container_name: shinobi
    hostname: shinobi
    restart: unless-stopped
    user: root
    runtime: nvidia # if using dev tag, that line can be dropped
    environment:
      - DB_USER=DB_USERNAME
      - DB_PASSWORD=DB_PASSWORD
      - DB_HOST=DB_HOSTNAME_OR_IP
      - DB_DATABASE=DB_NAME
      - DB_DISABLE_INCLUDED=true
      - EMBEDDEDDB=false
      - ADMIN_USER=SUPER_MAIL
      - ADMIN_PASSWORD=SUPER_PASS
    volumes:
      - $PWD/shinobi/config:/config
      
      - $PWD/shinobi/customAutoLoad:/home/Shinobi/libs/customAutoLoad
      - $PWD/shinobi/customAutoLoad:/customAutoLoad
      - $PWD/shinobi/database:/var/lib/mysql
      
      - $PWD/shinobi/videos:/home/Shinobi/videos
      
      - /dev/shm/streams-test:/dev/shm/streams
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

    ports:
      - 8080:8080/tcp
    
```
